#! /bin/sh

# Set up monitors
case $HOSTNAME in
	archStation)
		bspc monitor DP-5 -d T B W C M1
		bspc monitor DVI-D-0 -d F M S I M2
		bspc monitor HDMI-0 -d R L M3
		bspc config border_width         	1
		bspc config window_gap          	8
		;;
	archPad)
		bspc monitor -d T F B R W M C S I L M1 M2 M3
		bspc config border_width         	2
		bspc config window_gap          	16
		;;
	*)
		bspc monitor -d T F B R W M C S I L M1 M2 M3
		bspc config border_width         	1
		bspc config window_gap          	8
		;;
esac

# Start sxhkd -- single instance
pkill sxhkd
sxhkd &

# Launch polybar & dunst (to force reload with wm)
$HOME/.config/polybar/launch.sh
$HOME/.config/dunst/launch.sh

# Border colors
bspc config normal_border_color 	"#707880"
bspc config focused_border_color 	"#82AAFF"
bspc config urgent_border_color 	"#FFCC00"
bspc config presel_border_color 	"#8BD649"

# Layout
bspc config split_ratio          	0.50
bspc config single_monocle   		true
bspc config borderless_monocle   	false
bspc config gapless_monocle      	false

# Behavior
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
bspc config focus_follows_pointer	false
bspc config pointer_follows_monitor	true
bspc config ignore_ewmh_focus		true
bspc config external_rules_command 	$HOME/.config/bspwm/floating_preferences

# Organize windows

# Assign windows to workspaces
bspc rule -a Thunar 			desktop=F
bspc rule -a firefox 			desktop=B
bspc rule -a Zathura			desktop=R
bspc rule -a Zotero			desktop=R
bspc rule -a "MATLAB R2019b - academic use" desktop=M state=floating
bspc rule -a "MATLAB R2019b"		desktop=M state=floating
bspc rule -a Comsollauncher		desktop=S state=floating
bspc rule -a SWT			desktop=S
bspc rule -a Pulseeffects		desktop=M2
bspc rule -a mpv		 	desktop=I
bspc rule -a Spotify 			desktop=L
bspc rule -a keepassxc			desktop=M1
bspc rule -a "Syncthing GTK"		desktop=M1
bspc rule -a Pulseeffects		desktop=M2

# Floating/tiled windows
bspc rule -a Nitrogen	 		state=floating
bspc rule -a qt5ct	 		state=floating
bspc rule -a Arandr 			state=floating
bspc rule -a Pavucontrol		state=floating
bspc rule -a Lxappearance		state=floating
bspc rule -a Transmission-gtk 		state=floating
bspc rule -a Oblogout	 		state=fullscreen monitor='^1'
bspc rule -a Xarchiver	 		state=floating
bspc rule -a Nm-connection-editor	state=floating
bspc rule -a Gnome-system-monitor	state=floating
bspc rule -a Zathura			state=tiled
