#! /bin/sh

# Start sxhkd -- single instance
pkill sxhkd
sxhkd &

# Launch polybar
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	2
bspc config window_gap          	15

# Border colors
bspc config normal_border_color 	"#707880"
bspc config focused_border_color 	"#82AAFF"
bspc config urgent_border_color 	"#FFCC00"
bspc config presel_border_color 	"#8BD649"

# Layout
bspc config split_ratio          	0.50
bspc config single_monocle   		true
bspc config borderless_monocle   	false
bspc config gapless_monocle      	false

# Behavior
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
bspc config focus_follows_pointer	false
bspc config ignore_ewmh_focus		true

# Organize windows

# Assign windows to workspaces
bspc rule -a Thunar 			desktop='^2'
bspc rule -a firefox 			desktop='^3'
bspc rule -a Zathura			desktop='^4'
bspc rule -a MATLAB R2019a - academic use desktop='^6'
bspc rule -a Pulseeffects		desktop='^8'
bspc rule -a mpv		 	desktop='^9'
bspc rule -a Spotify 			desktop='^10'

# Floating/tiled windows
bspc rule -a Nitrogen	 		state=floating
bspc rule -a Arandr 			state=floating
bspc rule -a Pavucontrol		state=floating
bspc rule -a Transmission-gtk 		state=floating
bspc rule -a Oblogout	 		state=floating
bspc rule -a Xarchiver	 		state=floating
bspc rule -a Nm-connection-editor	state=floating
bspc rule -a Gnome-system-monitor	state=floating
bspc rule -a Zathura			state=tiled
