" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

" base16 color schemes
Plug 'chriskempson/base16-vim'
let base16colorspace=256

" Latex
Plug 'lervag/vimtex'
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'

" Snippets
Plug 'sirver/ultisnips'
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/UltiSnips']

" sxhkd syntax highlighting
Plug 'baskerville/vim-sxhkdrc'

" Initialize plugin system
call plug#end()

colorscheme base16-materia
hi Normal ctermbg=None

" Behavior settings
set number
set incsearch
set ignorecase
set smartcase
set smarttab
set splitbelow
set splitright
set exrc
set secure
set dictionary=/usr/share/dict/american-english

" Mappings
map <f9> :make
