" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

" base16 color schemes
Plug 'chriskempson/base16-vim'
let base16colorspace=256

" Latex
Plug 'lervag/vimtex'
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
let g:vimtex_latexmk_options = '-pdf -verbose -bibtex -file-line-error -synctex=1 --interaction=nonstopmode'
set conceallevel=1
let g:tex_conceal='abdmg'

" Matlab
Plug 'yinflying/matlab.vim'

" Snippets
Plug 'sirver/ultisnips'
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/UltiSnips']
let g:UltiSnipsUsePythonVersion = 2
let g:UltiSnipsEditSplit = 'tabdo'

" sxhkd syntax highlighting
Plug 'baskerville/vim-sxhkdrc'

" jupyter-vim for interactive python
Plug 'jupyter-vim/jupyter-vim'

" Initialize plugin system
call plug#end()

colorscheme base16-materia
hi Normal ctermbg=None

" Behavior settings
set number
set incsearch
set ignorecase
set smartcase
set smarttab
set splitbelow
set splitright
set dictionary=/usr/share/dict/american-english

" Tabs and splits
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Cut and copy
nnoremap Y y$
nnoremap D d$
nnoremap C c$

" Syntax checking
autocmd BufEnter *.m    compiler mlint
